const ACTIONS = {

  // Restore deleted item types
  SAVE_DELETED: "SAVE_DELETED",
  RESTORE_DELETED: "RESTORE_DELETED",

  // Activate and deactivate search
  UPDATE_SEARCH_STATUS: "UPDATE_SEARCH_STATUS",

  // Filter todos
  UPDATE_FILTER: "UPDATE_FILTER",

  // Set todos
  CLEAR_TODOS: "CLEAR_TODOS",
  SET_ALL_TODOS: "SET_ALL_TODOS",
  SET_TODOS_WHERE: "SET_TODOS_WHERE",
  ADD_TODOS: "ADD_TODOS",
  DELETE_TODO: "DELETE_TODO",
  MARK_OLD: "MARK_OLD",
  RESTORE_TODO: "RESTORE_TODO",

  // Set error message
  SET_SERVER_ERROR_MESSAGE: "SET_SERVER_ERROR_MESSAGE",

  // Loaded
  SET_IS_LOADED: "SET_IS_LOADED"
};

export default ACTIONS;
